// -----------------------------------------------------------------------------
// <auto-generated>
//  this code was generated from a template.
//
//  manual changes to this file may cause unexpected behavior in your app.
//  manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
// -----------------------------------------------------------------------------
import { Generator, GenerationParams } from "@vlr/razor/types";
import { ReducerGenModel } from "../types";

function generate(model: ReducerGenModel, params: GenerationParams): string {
    const gen = new Generator(params);
    generateContent(gen, model);
    return gen.toString();
}

function generateContent(gen: Generator, model: ReducerGenModel): void {
    const indent = gen.indent;
    for (let imp of model.imports) {
        gen.append(`import `);
        gen.append((imp.imported).toString());
        gen.append(` from `);
        gen.apostrophe();
        gen.append((imp.path).toString());
        gen.apostrophe();
        gen.append(`;`);
        gen.eol();
    }
    gen.forceEol();
    gen.indent = indent;
}

export const reducerGenerator = {
    generate,
    generateContent
};
